spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test2
    username: nilu
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

